// <auto-generated />
using System;
using KursManager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KursManager.Migrations
{
    [DbContext(typeof(KursDBContext))]
    [Migration("20240923191548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("KursManager.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dates")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trainer")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kurs");
                });

            modelBuilder.Entity("KursManager.Teilnehmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KursId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.ToTable("Teilnehmer");
                });

            modelBuilder.Entity("KursManager.Teilnehmer", b =>
                {
                    b.HasOne("KursManager.Kurs", "Kurs")
                        .WithMany("TeilnehmerList")
                        .HasForeignKey("KursId");

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("KursManager.Kurs", b =>
                {
                    b.Navigation("TeilnehmerList");
                });
#pragma warning restore 612, 618
        }
    }
}
